/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Persistencia.AuditoriaJpaController;
import Negocio.Auditoria;
import Negocio.Bien;
import Negocio.Inventario;
import Negocio.Usuario;
import Utilidades.FechaHora;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Persistencia.BienJpaController;
import Persistencia.UsuarioJpaController;

/**
 *
 * @author diego
 */
public class FrmAuditoria extends javax.swing.JDialog {
    
    AuditoriaJpaController dao = new AuditoriaJpaController();
    List<Auditoria> registros = new ArrayList();
    DefaultTableModel modelo = new DefaultTableModel();
    Integer tipoBusqueda = 1;
    
    private Usuario user;

    /**
     * Creates new form FrmAuditoria
     */
    public FrmAuditoria(java.awt.Frame parent, boolean modal) {
       // super(parent, modal);
        initComponents();
        this.colocarEncabezadoGrid();
    }
    public final void colocarEncabezadoGrid(){
        String[] columnNames = {"Fecha",
                                "Bien",
                                "Operacion",
                                "Usuario"};
        this.modelo.setColumnIdentifiers(columnNames);
        this.tblRegistros.setModel(this.modelo);
    }
    
    public void registrosPorBien(Bien unBien){
        this.registros = dao.findAuditoriaByBien(unBien);
    }

    public void setUser(Usuario user) {
        this.user = user;
    }
    
    
    
    public void registrosPorUsuario(Usuario usuario){
        this.registros = dao.findAuditoriaByUsuario(usuario);
    }
    public void registros(){
        this.registros = dao.findAuditoriaEntities();
    }
    
    public void buscarPorBien(){
        this.registrosPorBien(this.obtenerBien());
        if(this.registros.isEmpty()){
            showNoResults("Registros");
        }else{
            cargarGrid();
        }
    }
    
    public void buscarPorUsuario(){
        this.registrosPorUsuario(this.obtenerUsuario());
                if(this.registros.isEmpty()){
            showNoResults("Registros");
        }else{
            cargarGrid();
        }
    }
    
    public Bien obtenerBien(){
        Bien salida = null;
        BienJpaController daoBien = new BienJpaController();
        Integer nro = Integer.parseInt(this.txtBusqueda.getText());
        //List<Bien> bienes = daoBien.findBienByNroInventario(nro);
        List<Bien> bienes = daoBien.findBienByNroInventario(nro);
        
        if(bienes.size() > 0){
            salida = bienes.get(0);
        }
        return salida;
    }
    
    public Usuario obtenerUsuario(){
        UsuarioJpaController daoUser = new UsuarioJpaController();
        String userName = this.txtBusqueda.getText();
        Usuario salida  = daoUser.findUsuarioByUserName(userName);
        return salida;        
    }
    
    private void showNoResults(String campo) {
        JOptionPane.showMessageDialog(this,
            "No se encontraron bienes activos con ese " + campo,        
            "Algo salió mal",                        
            JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void buscarRegistros(){
        this.registros();
        
        if(this.registros.isEmpty()){
            showNoResults("Registros");
        }else{
            cargarGrid();
        }
    }
    
     public final void cargarGrid(){
       // Inventario inv = new Inventario();
        int cantregistros = this.registros.size();
        int COLS = 4;
        Object[][] data = new Object[cantregistros][COLS];
        int rowIndex = 0;
        
        for (Auditoria auditoria : this.registros) {
            data[rowIndex][0] = auditoria.getFecha();
            data[rowIndex][1] = auditoria.getBien();
            data[rowIndex][2] = auditoria.getOperacion();
            data[rowIndex][3] = auditoria.getUsuario();  
                    
            modelo.addRow(data[rowIndex]);
            rowIndex = rowIndex + 1;
        }
        this.tblRegistros.setModel(modelo);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnBien = new javax.swing.JRadioButton();
        btnUser = new javax.swing.JRadioButton();
        txtBusqueda = new javax.swing.JTextField();
        btnTodo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registros Auditoria - Patrimonio");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnBien);
        btnBien.setText("Bien");
        btnBien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBienActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnUser);
        btnUser.setText("Usuario");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnTodo);
        btnTodo.setSelected(true);
        btnTodo.setText("Todo");
        btnTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBien)
                .addGap(18, 18, 18)
                .addComponent(btnUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTodo)
                .addGap(10, 10, 10)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnBien)
                    .addComponent(btnUser)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTodo))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        tblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Bien", "Operacion", "Usuario"
            }
        ));
        jScrollPane1.setViewportView(tblRegistros);

        jButton1.setText("Aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        switch(this.tipoBusqueda){
            case 1:
                this.buscarRegistros();
                break;
            case 2:
                this.buscarPorBien();
                break;
            case 3:
                this.buscarPorUsuario();
                break;
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBienActionPerformed
        // TODO add your handling code here:
        this.tipoBusqueda = 2;
    }//GEN-LAST:event_btnBienActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        this.tipoBusqueda = 3;
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodoActionPerformed
        // TODO add your handling code here:
        this.tipoBusqueda = 1;
    }//GEN-LAST:event_btnTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmAuditoria dialog = new FrmAuditoria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnBien;
    private javax.swing.JRadioButton btnTodo;
    private javax.swing.JRadioButton btnUser;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRegistros;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
