/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.Bien;
import Negocio.Usuario;
import Persistencia.BienJpaController;
import Persistencia.exceptions.NonexistentEntityException;
import Utilidades.FechaHora;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class FrmBajaBien extends javax.swing.JDialog {

    /**
     * Creates new form FrmBajaBien
     */
    private Bien unBien;
    
    private Usuario user;
    private BienJpaController dao = new BienJpaController();
    
    public FrmBajaBien(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        initComponents();
        this.activarComponentes(false);
        
    }
    
    public void inicializar(){
        this.inicializarCampos();
        this.inicializarTiposBaja();

    }
     
    public void inicializarTiposBaja(){
        this.txtTipo.removeAllItems();
        this.txtTipo.addItem("Hurto");
        this.txtTipo.addItem("Destruccion");
        this.txtTipo.addItem("Natural");
        
        
    }

    public Usuario getUser() {
        return user;
    }

    public void setUser(Usuario user) {
        this.user = user;
    }
     
    public void setBien(Bien unBien){
        this.unBien = unBien;
    }

     public void activarComponentes(boolean var ){
         this.btnBaja.setEnabled(var);
         this.btnCancelar.setEnabled(!var);
         this.btnSalir.setEnabled(!var);
     }
    
    
    public final void inicializarCampos(){
       // this.txtNroInventario.setText(this.unBien.getNroInventario().toString());
        FechaHora fecha = new FechaHora();
        this.btnBaja.setEnabled(true);
        
        if(this.unBien.getDescripcion() != null){
            this.txtDescripcion.setText(this.unBien.getDescripcion());
        }
        
        if(this.unBien.getNroInventario() != null){
            this.txtNroInventario.setText(this.unBien.getNroInventario().toString());
        }
        
        if(this.unBien.getFechaBaja() != null){
            this.txtFechaBaja.setText(fecha.DateToString(this.unBien.getFechaBaja()));
        }else{
            this.txtFechaBaja.setText(fecha.DateToString(fecha.fechaActual()));
        }
        
        if(this.unBien.getResolucionBaja() != null){
            this.txtResolucionBaja.setText(this.unBien.getResolucionBaja());
        }
        
        this.inicializarTiposBaja();
        
        if(this.unBien.getTipoBaja() != null){
            this.txtTipo.setSelectedItem(this.unBien.getTipoBaja());
        }
        
    }
    public final void limpiarCampos(){
        this.txtFechaBaja.setText(null);
        this.txtNroInventario.setText(null);
        this.txtResolucionBaja.setText(null);
        this.txtDescripcion.setText(null);
        this.unBien = null;
    }
    
    public void buscarBien(){
        //this.unBien = this.logica.porNroInventario(Integer.decode(this.txtNroInventario.getText())).get(0);
        List<Bien> lista = this.dao.findBienByNroInventario(Integer.parseInt(this.txtNroInventario.getText()));
        this.limpiarCampos();
        if(lista.size() > 0){
            this.unBien = lista.get(0);
        }else{
            JOptionPane.showMessageDialog(null, "No se encontro ningun bien con el nro ingresado.");
        }
        this.inicializarCampos();
        
        
        
    }
    
    public Bien getBienFromForm(){
        FechaHora fecha = new FechaHora();
        String resolucion = this.txtResolucionBaja.getText();
        String tipoBaja = (String) this.txtTipo.getSelectedItem();
        Date fechaBaja = fecha.StringToDate(this.txtFechaBaja.getText());
        BigDecimal valor = new BigDecimal(1);
        
        return new Bien(
        this.unBien.getCodigo(),
        this.unBien.getNroInventario(),
        this.unBien.getDescripcion(), 
        this.unBien.getFechaAlta(), 
        this.unBien.getNroActa(), 
        valor, 
        "BAJA", 
        true, 
        this.unBien.getNroExpedienteAlta(),  
        this.unBien.getResolucionAlta(),  
        this.unBien.getNroExpedienteBaja(),  
        resolucion, 
                "",  
        fechaBaja,  
        tipoBaja);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        txtFechaBaja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtResolucionBaja = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNroInventario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        Descripcion = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baja de Bienes");
        setResizable(false);

        jLabel2.setText("Fecha");

        txtFechaBaja.setName("txtFecha"); // NOI18N

        jLabel4.setText("Resolucion");

        txtResolucionBaja.setName("txtResolucion"); // NOI18N

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnBaja.setText("Baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        jLabel6.setText("Nro de Inventario");

        txtNroInventario.setToolTipText("");
        txtNroInventario.setName("txtNroInventario"); // NOI18N
        txtNroInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroInventarioActionPerformed(evt);
            }
        });
        txtNroInventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNroInventarioKeyPressed(evt);
            }
        });

        jLabel1.setText("Tipo");

        txtTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        Descripcion.setText("Descripcion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtResolucionBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNroInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFechaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel4)
                            .addComponent(Descripcion))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNroInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtFechaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtResolucionBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Descripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnCancelar)
                    .addComponent(btnBaja))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:

            int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea salir?", "Confirmación", JOptionPane.YES_NO_OPTION);
            switch(respuesta) {
                case JOptionPane.YES_OPTION:
                    //--- Operaciones en caso afirmativo
                    this.dispose();
                    break;
            }            
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        // TODO add your handling code here:
        FechaHora fecha = new FechaHora();        
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea dar de Baja el Bien?", "Confirmación", JOptionPane.YES_NO_OPTION);
            switch(respuesta) {
                case JOptionPane.YES_OPTION:
                try{
                    Bien newBien = this.getBienFromForm();
                    this.dao.baja(newBien, this.unBien.getId(),this.getUser());    
                }
            catch (NonexistentEntityException e){
              JOptionPane.showMessageDialog(null, "No se puede guardar la infomación.\nDebe completar los datos requeridos.");  
            }    
                    break;
            }
            
            this.activarComponentes(false);
            
            this.limpiarCampos();
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.unBien = null;
        this.txtFechaBaja.setText(null);
        this.txtNroInventario.setText(null);
        this.txtResolucionBaja.setText(null);
        this.txtDescripcion.setText(null);
        
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNroInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroInventarioActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_txtNroInventarioActionPerformed

    private void txtNroInventarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroInventarioKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10){
            this.buscarBien();
        }
    }//GEN-LAST:event_txtNroInventarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBajaBien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBajaBien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBajaBien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBajaBien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmBajaBien dialog = new FrmBajaBien(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripcion;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtFechaBaja;
    private javax.swing.JTextField txtNroInventario;
    private javax.swing.JTextField txtResolucionBaja;
    private javax.swing.JComboBox<String> txtTipo;
    // End of variables declaration//GEN-END:variables
}
